language: php
php:
  - 7.1
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --optimize-autoloader

script:
  - composer test
  - composer cs-check
  - composer stan

notifications:
  email: false
