language: php
php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src/ tests/
  - vendor/bin/phpstan analyze -l 1 src/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email: false
