language: php
php:
  - 7.1
  - 7.4

install:
  - composer install --no-interaction --optimize-autoloader

script:
  - composer test
  - composer cs-check
  - composer stan

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
