language: php
php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src
  - vendor/bin/phpstan analyze src/ -l 1

notifications:
  email: false
